/**
 * @open-slidestudio/pptd-v2
 *
 * Kimi YAML PPTD v2 — sole document SSOT for native offline stack.
 */

export type * from "./types.js";
export {
  WRITE_PAGE_PARAMETER_SPEC,
  PPTD_ELEMENT_PARAMETER_SPEC,
  EDIT_ELEMENTS_PARAMETER_SPEC,
  writePageJsonSchema,
  editElementsJsonSchema,
  canonicalWritePageIssues,
  canonicalEditElementsIssues,
  canonicalFillIssues,
  canonicalTextStylePatchIssues,
  isCanonicalWritePageArgs,
  isCanonicalEditElementsArgs,
  coerceLineArrowHead,
  normalizeWritePageLineArrows,
  normalizeWritePageDialect,
  type CanonicalWritePageArgs,
  type CanonicalEditElementsArgs,
} from "./write-page-schema.js";
export {
  categoricalChartModel,
  chartKind,
  placeScatterLabels,
  scatterChartModel,
  waterfallChartModel,
  type CategoricalChartModel,
  type CategoricalChartSeries,
  type ScatterChartModel,
  type ScatterLabelPlacement,
  type ScatterLabelPoint,
  type ScatterPoint,
  type SupportedChartKind,
  type WaterfallBar,
  type WaterfallChartModel,
} from "./chart-semantics.js";
export {
  CHART_GRID,
  CHART_INK,
  CHART_PALETTE,
  CHART_TEXT_PX,
  alignedSecondaryScale,
  chartLayout,
  chartNumberFormatCode,
  chartSwatch,
  chartZeroHiddenFormatCode,
  formatChartValue,
  measureChartText,
  niceScale,
  resolveChartLegend,
  seriesDecimals,
  type ChartLayout,
  type ChartLayoutOptions,
  type ChartScale,
  type LegendLayout,
  type LegendPosition,
  type LegendSpec,
  type Point,
  type Rect,
} from "./chart-layout.js";
export {
  DEFAULT_TEXT_LINE_HEIGHT,
  TEXT_LAYOUT_CONTRACT_V1,
  effectiveLayoutRole,
  footerZoneTopForSlide,
  type TextLayoutContractV1,
} from "./text-layout.js";
export {
  loadProject,
  saveProject,
  withProjectWriteLock,
  createEmptyProject,
  titleOnlyCoverPage,
  listComposedPage,
  calculateMaterialFingerprint,
  PptdError,
} from "./parse.js";
export {
  SHAPE_ALIASES,
  SHAPE_CATALOG,
  SHAPE_BY_NAME,
  SUPPORTED_SHAPE_NAMES,
  canonicalShapeName,
  isSupportedShapeName,
  shapeDefaults,
  type ShapeInfo,
} from "./shape-catalog.js";
export { shapePath, shapeSvg, shapeGeometry, adjUnit } from "./shape-path.js";
export {
  ooxmlShapePath,
  ooxmlPresetNames,
  ooxmlShapeGeometry,
  ooxmlAdjustHandles,
  type AdjustHandle,
  type ShapeGeometry,
} from "./ooxml-geom.js";
export {
  CHART_FONT_FACE,
  DEFAULT_FONT_PAIR,
  SLIDE_FONTS,
  canonicalFontName,
  defaultThemeTextStyles,
  fontCss,
  fontEntry,
  isSlideFont,
  normalizeFontFamily,
  normalizePageFonts,
  resolveFontPair,
  type FontEntry,
  type FontPair,
  type FontReplacement,
  type FontScript,
} from "./font-policy.js";
export {
  resolveThemeColor,
  officialPptdColorKind,
  InvalidPptdColorError,
  toRgbHex,
  colorAlpha,
  relativeLuminance,
  contrastRatio,
  shapePaintFill,
  elementFillPaint,
  svgFillFromFillCss,
  stripHtmlToText,
  parseRichText,
  serializeRichText,
  applyRangeStyle,
  toCssColor,
  unescapePlainText,
  resolveTextStyle,
  type ResolvedTextStyle,
  type RichTextRun,
  type RangeStylePatch,
  type OfficialPptdColorKind,
  type ShapePaintFill,
  type ElementFillPaint,
} from "./theme.js";
